#!/bin/sh

Main() {
  if [ "$env" = "" ]
  then
    echo "Linux Dev Environment Setup"
    echo "------------------------------------------"
    echo "Options:"
    echo
    echo "1. Install Ruby Dev Enviroment on KDE"
    echo "0. Exit"
    echo
    echo -n "Choose an option:"
    read option
    case $option in
      1) RubyKDE ;;
      0) exit ;;
      *) "Option unknown" ; echo ; Main ;;
    esac
  else
    case $env in
      ruby) RubyKDE ;;
      *) echo "Environment unknown" ; exit ;;
    esac
  fi
}

RubyKDE(){
  sudo apt-get install -y kde-full
  add_repos
  sudo apt-get update
  add_keys
  sudo apt-get update
  sudo apt-get dist-upgrade
  install_basic_pkgs
  install_vim
  install_browsers
  install_database
  install_sunjava
  install_git
  install_nodejs
}

add_repos(){
sudo cat <<EOF >> /etc/apt/sources.list

#Backports
deb http://backports.debian.org/debian-backports squeeze-backports main

#Debian-Multimedia
deb http://www.debian-multimedia.org squeeze main non-free

#Dotdeb
deb http://packages.dotdeb.org squeeze all
deb-src http://packages.dotdeb.org squeeze all

#Opera
deb http://deb.opera.com/opera-beta/ squeeze non-free

#Google
deb http://dl.google.com/linux/deb/ stable main non-free
deb http://dl.google.com/linux/talkplugin/deb/ stable main

#Mozilla
deb http://mozilla.debian.net/ squeeze-backports iceweasel-release
EOF
}

add_keys(){
  sudo apt-get install debian-multimedia-keyring
  wget -q -O - http://www.dotdeb.org/dotdeb.gpg | sudo apt-key add -
  wget -O - http://deb.opera.com/archive.key | sudo apt-key add -
  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  wget http://mozilla.debian.net/pkg-mozilla-archive-keyring_1.0_all.deb
  sudo dpkg -i pkg-mozilla-archive-keyring_1.0_all.deb
  rm pkg-mozilla-archive-keyring_1.0_all.deb
  wget -q -O - http://www.dotdeb.org/dotdeb.gpg | sudo apt-key add -
}

install_basic_pkgs(){
  sudo apt-get install -y gcc make smplayer unrar amarok bash curl
}

install_vim(){
  sudo apt-get install -y vim exuberant-ctags ncurses-term
  git clone git@github.com:plribeiro3000/vimfiles.git ~/.vim
  cd ~/.vim
  git submodule update --init
  echo "source ~/.vim/vimrc" > ~/.vimrc
}

install_browsers(){
  sudo apt-get install -y opera google-chrome-unstable
  sudo apt-get install -t squeeze-backports iceweasel
}

install_database(){
  sudo apt-get install -y mysql-query-browser mysql-client mysql-server
}

install_sunjava(){
  sudo apt-get install -y sun-java6*
  sudo apt-get remove openjdk*
  sudo update-java-alternatives -l
  sudo update-java-alternatives -s java-6-sun
}

install_git(){
  sudo apt-get install -y git-core git-flow qgit
  wget https://raw.github.com/git/git/master/contrib/completion/git-completion.bash -O ~/.git-completion
  echo "source ~/.git-completion" >> ~/.bashrc
}

install_nodejs(){
  echo "deb http://ftp.us.debian.org/debian/ sid main" > tmp
  sudo mv tmp /etc/apt/sources.list.d/sid.list
  sudo apt-get update
  sudo apt-get install -y nodejs
  sudo rm /etc/apt/sources.list.d/sid.list
  sudo apt-get update
}

display_help(){
  echo "help"
}

env=
verbose=false
default=false
while [ $# -gt 0 ]
do
  case "$1" in
    -e)	env="$2" ;;
    -v)	verbose=true ;;
    -d)	default=true ;;
    -h)	display_help
	exit;;
  esac
  shift
done

Main